Excel upload + View Table uploaded Students
Bacio001-CCG/Project-Sint-Scholen-Groep-A pull request #25
Opened 2024-03-07 19:19 UTC by Kutatsu

2024-03-07 19:28 UTC, Bacio001-CCG requested changes
Please fix the requests before merging.

2024-03-07 19:28 UTC, Bacio001-CCG commented on app/Http/Controllers/StudentController.php
Even though \Maatwebsite\Excel\Validators\ValidationException is a valid way of importing, I would suggest doing it at the top of the file and just referencing the part you need

2024-03-07 19:28 UTC, Bacio001-CCG commented on app/Imports/UsersImport.php
Errors are in english but they need to be displayed in dutch

2024-03-07 19:28 UTC, Bacio001-CCG commented on app/Http/Controllers/StudentController.php
Remove the comments if not used

2024-03-07 19:28 UTC, Bacio001-CCG commented on composer.lock
This is not supposed to come with it mind putting it in the .ignore if it isn't already

2024-03-07 19:28 UTC, Bacio001-CCG commented on database/factories/DeanFactory.php
Make sure that these factories don't break the factories from development up on merging pls

2024-03-07 19:28 UTC, Bacio001-CCG commented on package-lock.json
This also should be in the .gitignore

2024-03-07 19:28 UTC, Bacio001-CCG commented on resources/views/users.blade.php
Not really sure what this is supposed to be but I don't think you want an empty body with just a script tag. Please keep import and script stuff in the layout files, also use our layout in general.

2024-03-07 19:34 UTC, MikeWhileCoding requested changes

2024-03-07 19:34 UTC, MikeWhileCoding commented on app/Http/Controllers/StudentController.php
> +            //  }
```suggestion
```

Remove commented code if not needed

2024-03-07 19:34 UTC, MikeWhileCoding commented on database/factories/DeanFactory.php
Make sure to merge factory from dev unless there is a big difference, then merge it right

2024-03-07 19:34 UTC, MikeWhileCoding commented on resources/views/users.blade.php
No content except for header? Is there a future need for this?

2024-03-07 19:34 UTC, MikeWhileCoding commented on routes/web.php
Look at the new way of the route grouping

2024-03-07 19:34 UTC, MikeWhileCoding commented on tests/Unit/StoreFunctionUnitTest.php
Do these test work? Naming is different from the already existing tests in dev

2024-03-07 19:34 UTC, MikeWhileCoding commented on tests/Unit/UsersImportUnitTest.php
Same as other test

2024-03-08 12:37 UTC, Bacio001-CCG commented on tests/Unit/StoreFunctionUnitTest.php
These probably don't run naming convention are wrong I'm 99% sure

2024-03-08 14:26 UTC, Kutatsu commented
@ITZZwilco Needs to look at the factory issue, because i didn't touch that so no idea what happened there.

2024-03-08 14:28 UTC, MikeWhileCoding commented
> @ITZZwilco Needs to look at the factory issue, because i didn't touch that so no idea what happened there.

I know what happened here 😄 You added the school_id. I will check and fix the merge conflics in minute

2024-03-08 14:31 UTC, Bacio001-CCG approved these changes

2024-03-08 14:40 UTC, MikeWhileCoding approved these changes

2024-03-08 14:43 UTC, merged